# app.py — Streamlit app for the Adult Income classification models
# Loads the models saved by train_models.py, evaluates them on data you upload.

import os
import joblib
import numpy as np
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.metrics import (
    accuracy_score, roc_auc_score, precision_score, recall_score,
    f1_score, matthews_corrcoef, confusion_matrix, classification_report,
)

# ---- page setup ----
st.set_page_config(page_title="Adult Income Model Explorer — Rijas", layout="wide")
st.title("Adult Income Classification — Model Explorer")
st.write(
    "This app compares five classifiers trained on the UCI Adult Income "
    "dataset. Upload the test CSV generated by train_models.py, pick a "
    "model, and review its metrics, confusion matrix, and classification report."
)

TARGET    = "income"
MODEL_DIR = "model"
MODEL_FILES = {
    "Logistic Regression": "logistic_regression.joblib",
    "Decision Tree":       "decision_tree.joblib",
    "kNN":                 "knn.joblib",
    "Naive Bayes":         "naive_bayes.joblib",
    "Random Forest":       "random_forest.joblib",
}


@st.cache_resource
def load_encoder():
    return joblib.load(os.path.join(MODEL_DIR, "label_encoder.joblib"))


@st.cache_resource
def load_model(fname):
    return joblib.load(os.path.join(MODEL_DIR, fname))


encoder = load_encoder()

# ---- sidebar ----
st.sidebar.header("About")
st.sidebar.write("Built by Rijas — BITS Pilani WILP, M.Tech AIML, ML Assignment 2.")
st.sidebar.write(f"Target column: `{TARGET}` (<=50K / >50K)")

# ---- 1. CSV upload ----
uploaded = st.file_uploader("Upload test_data.csv", type="csv")

if uploaded is not None:
    df = pd.read_csv(uploaded)
    st.subheader("Preview of uploaded data")
    st.dataframe(df.head())

    # clean '?' junk values the same way train_models.py did
    df = df.replace("?", np.nan)

    if TARGET not in df.columns:
        st.error(f"Uploaded file must contain a '{TARGET}' column.")
        st.stop()

    X = df.drop(columns=[TARGET])
    y = encoder.transform(df[TARGET])

    # ---- 2. model dropdown ----
    choice = st.selectbox("Choose a model", list(MODEL_FILES.keys()))
    model = load_model(MODEL_FILES[choice])

    y_pred = model.predict(X)
    y_proba = model.predict_proba(X)[:, 1]

    # ---- 3. metrics display ----
    st.subheader(f"Metrics — {choice}")
    metrics = {
        "Accuracy":  accuracy_score(y, y_pred),
        "AUC":       roc_auc_score(y, y_proba),
        "Precision": precision_score(y, y_pred, zero_division=0),
        "Recall":    recall_score(y, y_pred, zero_division=0),
        "F1":        f1_score(y, y_pred, zero_division=0),
        "MCC":       matthews_corrcoef(y, y_pred),
    }
    cols = st.columns(3)
    for i, (name, value) in enumerate(metrics.items()):
        cols[i % 3].metric(name, f"{value:.3f}")

    # ---- 4. confusion matrix ----
    st.subheader("Confusion Matrix")
    cm = confusion_matrix(y, y_pred)
    fig, ax = plt.subplots()
    sns.heatmap(
        cm, annot=True, fmt="d", cmap="Purples",
        xticklabels=encoder.classes_, yticklabels=encoder.classes_, ax=ax,
    )
    ax.set_xlabel("Predicted")
    ax.set_ylabel("Actual")
    st.pyplot(fig)

    # ---- classification report (bonus detail) ----
    st.subheader("Classification Report")
    report = classification_report(
        y, y_pred, target_names=encoder.classes_, output_dict=True
    )
    st.dataframe(pd.DataFrame(report).T.round(3))
else:
    st.info("Waiting for a CSV upload to begin.")
