# app.py — Streamlit app for my ML Assignment 2 (Adult Income classification)
# Rijas, M.Tech AIML, BITS Pilani WILP
#
# Loads the 5 models trained by train_models.py and lets you try them out
# on uploaded test data. Two views: a comparison overview across all models,
# and a per-model deep dive with metrics + confusion matrix.

import os
import joblib
import numpy as np
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.colors import LinearSegmentedColormap

# my two-tone theme: sky blue for the low end, red for the high end
SKY_RED_CMAP = LinearSegmentedColormap.from_list("sky_red", ["#E0F2FE", "#0EA5E9", "#E63946"])
CHART_COLORS = ["#0EA5E9", "#38BDF8", "#7DD3FC", "#F87171", "#EF4444", "#DC2626"]

from sklearn.metrics import (
    accuracy_score, roc_auc_score, precision_score, recall_score,
    f1_score, matthews_corrcoef, confusion_matrix, classification_report,
)

INCOME_COLUMN   = "income"
MODELS_FOLDER   = "model"
MODEL_CATALOG = {
    "Logistic Regression": "logistic_regression.joblib",
    "Decision Tree":       "decision_tree.joblib",
    "kNN":                 "knn.joblib",
    "Naive Bayes":         "naive_bayes.joblib",
    "Random Forest":       "random_forest.joblib",
}

st.set_page_config(page_title="Adult Income Model Explorer — Rijas", layout="wide")

st.title("Adult Income Classification — Model Explorer")
st.caption("ML Assignment 2 · Rijas · BITS Pilani WILP, M.Tech AIML")
st.write(
    "I trained 5 classifiers on the UCI Adult Income census dataset to predict "
    "whether someone earns above or below $50K/year. This app lets you compare "
    "all 5 at a glance, then dig into any one of them on your own test data."
)

with st.sidebar:
    st.header("About this project")
    st.write(
        "Built for ML Assignment 2. The dataset is imbalanced "
        "(~76% earn <=50K, ~24% earn >50K), which is why I lean on AUC and "
        "MCC more than plain accuracy when judging a model here."
    )
    st.markdown("[Source code on GitHub](https://github.com/Rijas99/adult-income-ml-a2)")
    st.divider()
    st.caption("Rijas · M.Tech AIML")


@st.cache_resource
def get_label_encoder():
    return joblib.load(os.path.join(MODELS_FOLDER, "label_encoder.joblib"))


@st.cache_resource
def get_trained_model(filename):
    return joblib.load(os.path.join(MODELS_FOLDER, filename))


@st.cache_data
def get_comparison_table():
    path = os.path.join(MODELS_FOLDER, "metrics_comparison.csv")
    return pd.read_csv(path, index_col=0)


label_encoder = get_label_encoder()

overview_tab, explorer_tab = st.tabs(["Compare all 5 models", "Explore one model"])

# ---------------- TAB 1: quick comparison across all 5 models ----------------
with overview_tab:
    st.subheader("How the 5 models stack up")
    st.write("These numbers come straight from training (`model/metrics_comparison.csv`), on a 20% held-out split.")

    comparison = get_comparison_table()
    st.dataframe(comparison.style.highlight_max(axis=0, color="#0EA5E9"))

    # grouped bar chart — easier to eyeball than a plain table
    fig, ax = plt.subplots(figsize=(10, 4.5))
    comparison.plot(kind="bar", ax=ax, color=CHART_COLORS)
    ax.set_ylabel("Score")
    ax.set_xlabel("")
    ax.set_title("Metric comparison across models")
    ax.legend(loc="lower right", ncol=3, fontsize=8)
    plt.xticks(rotation=20, ha="right")
    st.pyplot(fig)

    best_by_mcc = comparison["MCC"].idxmax()
    st.info(f"By MCC (the most balanced metric for an imbalanced dataset like this one), **{best_by_mcc}** comes out on top.")

# ---------------- TAB 2: pick a model, upload data, inspect it ----------------
with explorer_tab:
    st.subheader("Try a model on your own test data")
    uploaded_csv = st.file_uploader("Upload test_data.csv", type="csv")

    if uploaded_csv is None:
        st.info("Waiting for a CSV upload — use the `test_data.csv` generated by train_models.py.")
        st.stop()

    raw_df = pd.read_csv(uploaded_csv)
    st.write("Preview:")
    st.dataframe(raw_df.head())

    # '?' is how this dataset marks missing values — same cleanup as training
    raw_df = raw_df.replace("?", np.nan)

    if INCOME_COLUMN not in raw_df.columns:
        st.error(f"This file needs an '{INCOME_COLUMN}' column to score against.")
        st.stop()

    features = raw_df.drop(columns=[INCOME_COLUMN])
    true_labels = label_encoder.transform(raw_df[INCOME_COLUMN])

    model_choice = st.selectbox("Pick a model", list(MODEL_CATALOG.keys()))
    model = get_trained_model(MODEL_CATALOG[model_choice])

    predicted_labels = model.predict(features)
    predicted_proba = model.predict_proba(features)[:, 1]

    left, right = st.columns([1, 1])

    with left:
        st.markdown(f"#### Metrics — {model_choice}")
        scores = {
            "Accuracy":  accuracy_score(true_labels, predicted_labels),
            "AUC":       roc_auc_score(true_labels, predicted_proba),
            "Precision": precision_score(true_labels, predicted_labels, zero_division=0),
            "Recall":    recall_score(true_labels, predicted_labels, zero_division=0),
            "F1":        f1_score(true_labels, predicted_labels, zero_division=0),
            "MCC":       matthews_corrcoef(true_labels, predicted_labels),
        }
        metric_cols = st.columns(2)
        for i, (metric_name, metric_value) in enumerate(scores.items()):
            metric_cols[i % 2].metric(metric_name, f"{metric_value:.3f}")

    with right:
        st.markdown("#### Confusion Matrix")
        cm = confusion_matrix(true_labels, predicted_labels)
        fig, ax = plt.subplots(figsize=(4.5, 4))
        sns.heatmap(
            cm, annot=True, fmt="d", cmap=SKY_RED_CMAP,
            xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_, ax=ax,
        )
        ax.set_xlabel("Predicted")
        ax.set_ylabel("Actual")
        st.pyplot(fig)

    with st.expander("Full classification report"):
        report = classification_report(
            true_labels, predicted_labels,
            target_names=label_encoder.classes_, output_dict=True,
        )
        st.dataframe(pd.DataFrame(report).T.round(3))
